const events = {
    PATIENT_CREATE: 'PATIENT_CREATE',
    PATIENT_SCHEMA_ERROR: 'PATIENT_SCHEMA_ERROR',
    PATIENT_GET_ALL: 'PATIENT_GET_ALL',
    PATIENT_GET_ONE: 'PATIENT_GET_ONE',
    PATIENT_REMOVE: 'PATIENT_REMOVE',
    PATIENT_GET_HISTORY: 'PATIENT_GET_HISTORY',
    PATIENT_UPDATE: 'PATIENT_UPDATE',
}

module.exports = { events }
