const actionsTypes = {
    HOME_ADD_LIST: 'HOME_ADD_LIST',
    HOME_SAVE: 'HOME_SAVE',
    HOME_SAVE_CANCEL: 'HOME_SAVE_CANCEL',
    HOME_SET_ERROR: 'HOME_SET_ERROR',
    HOME_LIST: 'HOME_LIST',
    HOME_SET_LIST: 'HOME_SET_LIST',
    HOME_EDIT: 'HOME_EDIT',
    HOME_SET_OBJ: 'HOME_SET_OBJ',
    HOME_REMOVE: 'HOME_REMOVE',
    HOME_REMOVE_LIST: 'HOME_REMOVE_LIST',
    HOME_UPDATE_LIST: 'HOME_UPDATE_LIST',
}

export { actionsTypes }
