version: '3.7'
services:
    database:
        container_name: database
        image: mysql:5.7
        env_file:
            - ./docker-compose.env
        networks:
            main:
                aliases:
                    - database
        ports:
            - 3306:3306
        volumes:
            - ./docker-entrypoint:/docker-entrypoint-initdb.d/

networks:
    main:
